---
- name: Add Grafana repo
  copy:
    content: |
      [grafana]
      name=grafana
      baseurl=https://rpm.grafana.com
      repo_gpgcheck=1
      enabled=1
      gpgcheck=1
      gpgkey=https://rpm.grafana.com/gpg.key
      sslverify=1
      sslcacert=/etc/pki/tls/certs/ca-bundle.crt
    dest: /etc/yum.repos.d/grafana.repo

- name: Install Grafana
  dnf:
    name: grafana
    state: present

- name: Start Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: true
