---
- name: Config Webservers
  hosts: webservers
  become: true

  roles:
    - nginx
    - node_exporter

- name: Setup Monitoring Server
  hosts: monitoring
  become: true
  roles:
    - prometheus
    - grafana