---
- name: Create prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin
    system: yes

- name: Download prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Create prometheus config
  copy:
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets:
              - '13.57.214.16:9100' 
              - '54.215.134.165:9100'
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus

- name: Create systemd service
  copy:
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service

- name: Start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: yes